---
title: "ETFs "
output: html_notebook
---

Here's a description about the results of session 10/24. 

* Prices of A, B and C above FV. 

* It's puzzling to see the high price of A and B compared to FV. 

* $p_A$ is double the price of FV. A risk aversion story falls short in explaining this behavior. 

* the price gap btw $p_B-p_A$ tends to stabilize around 11.0 in first stage for round 2. 

* what's the role of C? If a investor is holding $C$ then she should realize that it's value is way higher compared to the two underlying assets. it should sell it. but what happen if you hold it and A and B are way to overprice... so just keep it then!

* perhaps, we should endow every player with at least some $C$. 

* new endowments

  * type I : 6 2 2 
  * type II: 2 6 2 
  * type III: 2 2 6
  
* in a simple environment 

$$
u(c)
$$


$$
c + p x = w
$$  
We solve this backwards, so starting at time $T$, we have utility of holding A is 
$$
.5 \times u(11) + .5 \times u(9) 
$$
Assuming CARA


```{r}
ut<-function(g,x){
x^(1-g)/(1-g)
}
g<-0.7
eu<- 0.5*ut(g,11)+0.5*ut(g,9) # only A 
euab<- 0.5*ut(g,21)+0.5*ut(g,21)
ce <- (eu*(1-g))^(1/(1-g))
ce

```
The three trader types considered are proposed by DeLong et al. (1990, hereafter DSSW). 

(I) The persistence of bubbles suggests the existence of agents who trade on momentum, purchasing units after price increases as if they expect prices to continue rising, and selling rapidly once a crash occurs. ('trend extrapolators'?). Following DSSW, we denote these traders as feed- back traders. 

(II) The existence of a crash suggests that there are also traders in the population who speculate, but realize that speculation on an upward price movement is unlikely to be profitable very late in the time horizon and thus sell their units at that time, thereby precipitating a crash. We call these traders speculators.

(III) We also include the third type DSSW propose, passive investors, who trade based on fundamental values, purchasing (selling) when prices are below (above) fundamentals. [JP: other definition of passive trading is different. inactivity? you buy the index and sit on it. ]


Each subject receives a score with respect to each of the three types, with the score for each type equal to the number of periods in which subject’s behavior is consistent with that type.
A subject is classified as the type that receives the highest score, provided that the score is greater than 8, and as “other” otherwise. Ties are broken by assigning the corresponding fraction to each type. The number of subjects classified as each type is shown for each session,



















